include:
  - project: 'ci-templates/front'
    ref: v3.2.0
    file: '/templates/application.yml'

variables:
  DOCKER_IMAGE_NAME: $DOCKER_REGISTRY/frontend/recruitment/front-technical-test
  DOCKER_IMAGE_TAG: $CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA

deploy:docker:
  extends: .deploy:docker
  dependencies: []
  script:
    - echo $DOCKER_CI_PASSWORD | docker login -u $DOCKER_CI_LOGIN --password-stdin $DOCKER_REGISTRY
    - docker build -t $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG .
    - docker push $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
  only:
    - /^test.*$/
  except:
    - branches

deploy:review:
  extends: .deploy:review
  script:
    - |
      REVIEW_NAME="$CI_ENVIRONMENT_SLUG" \
      REVIEW_IMAGE="$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG" \
      envsubst < review.yml > deployment.yml
    - kube apply -f deployment.yml
  only:
    - /^test.*$/
  except:
    - branches

deploy:review:stop:
  extends: .deploy:review:stop
  only:
    - /^test.*$/
  except:
    - branches
